<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Import\Model\Processor;

use ReadyData\Import\Model\BatchContext;
use ReadyData\Import\Model\Cache\AttributeMetadataCache;
use ReadyData\Import\Model\Cache\StoreWebsiteMap;
use ReadyData\Import\Model\Config;
use ReadyData\Import\Model\ResourceModel\EavValue;
use ReadyData\Import\Model\ResourceModel\UrlRewrite;

/**
 * Regenerates direct product URL rewrites (url_key + suffix => product
 * view) for every store of the product's websites.
 *
 * Future expansions: category-path product rewrites, 301 redirects from
 * old url_keys, store-scoped url_key overrides.
 */
class UrlRewriteProcessor implements ProcessorInterface
{
    public function __construct(
        private readonly UrlRewrite $urlRewriteResource,
        private readonly EavValue $eavValue,
        private readonly AttributeMetadataCache $attributeMetadataCache,
        private readonly StoreWebsiteMap $storeWebsiteMap,
        private readonly Config $config
    ) {
    }

    public function process(BatchContext $context): void
    {
        $urlKeys = $this->resolveUrlKeys($context);
        $websiteIdsBySku = $context->get(WebsiteProcessor::CONTEXT_WEBSITE_IDS, []);
        $strategy = $this->config->getUrlRewriteConflictStrategy();

        // sku => [store_id => request_path]
        $candidates = [];
        foreach ($context->getValidProducts() as $sku => $product) {
            if (!isset($urlKeys[$sku]) || $urlKeys[$sku] === '' || $context->getEntityId($sku) === null) {
                continue;
            }
            $storeIds = $this->storeWebsiteMap->getStoreIdsForWebsites($websiteIdsBySku[$sku] ?? []);
            foreach ($storeIds as $storeId) {
                $candidates[$sku][$storeId] = $urlKeys[$sku] . $this->urlRewriteResource->getProductUrlSuffix($storeId);
            }
        }
        if (!$candidates) {
            return;
        }

        $allPaths = array_values(array_unique(
            array_merge(...array_values(array_map('array_values', $candidates)))
        ));
        $conflicts = $this->urlRewriteResource->findConflicts($allPaths, $context->getValidEntityIds());

        $rows = [];
        $touchedEntityIds = [];
        $touchedStoreIds = [];
        // Paths claimed by an earlier product in THIS batch, per store.
        // findConflicts only inspects the DB (and excludes our own batch
        // entities), so two same-batch products resolving to the same path
        // would both pass its check and then collapse into a single row via
        // insertOnDuplicate — one product silently loses its rewrite. Treat an
        // already-claimed path as a conflict so it is disambiguated too.
        $claimed = [];
        foreach ($candidates as $sku => $pathsByStore) {
            $entityId = $context->getEntityId((string)$sku);
            foreach ($pathsByStore as $storeId => $requestPath) {
                if (isset($conflicts[$storeId][$requestPath]) || isset($claimed[$storeId][$requestPath])) {
                    $requestPath = $this->resolveConflict($context, (string)$sku, $storeId, $requestPath, $strategy);
                    if ($requestPath === null) {
                        continue;
                    }
                }
                $claimed[$storeId][$requestPath] = true;
                $rows[] = [
                    'entity_type' => UrlRewrite::ENTITY_TYPE_PRODUCT,
                    'entity_id' => $entityId,
                    'request_path' => $requestPath,
                    'target_path' => 'catalog/product/view/id/' . $entityId,
                    'redirect_type' => 0,
                    'store_id' => $storeId,
                    'is_autogenerated' => 1,
                ];
                $touchedEntityIds[$entityId] = true;
                $touchedStoreIds[$storeId] = true;
            }
        }

        $this->urlRewriteResource->replaceProductRewrites(
            array_keys($touchedEntityIds),
            array_keys($touchedStoreIds),
            $rows
        );
    }

    /**
     * url_keys written this batch (from EavValueProcessor), backfilled with
     * the stored url_key for existing products the payload didn't touch.
     *
     * @return array<string, string> sku => url_key
     */
    private function resolveUrlKeys(BatchContext $context): array
    {
        $urlKeys = $context->get(EavValueProcessor::CONTEXT_URL_KEYS, []);
        $linkIds = $context->get(EntityProcessor::CONTEXT_LINK_IDS, []);

        $missingLinkIds = [];
        foreach ($context->getValidProducts() as $sku => $product) {
            if (!isset($urlKeys[$sku]) && isset($linkIds[$sku])) {
                $missingLinkIds[$linkIds[$sku]] = $sku;
            }
        }
        if ($missingLinkIds) {
            $meta = $this->attributeMetadataCache->get('url_key');
            if ($meta !== null) {
                $stored = $this->eavValue->getValues('varchar', $meta['attribute_id'], array_keys($missingLinkIds));
                foreach ($stored as $linkId => $urlKey) {
                    $urlKeys[$missingLinkIds[(int)$linkId]] = (string)$urlKey;
                }
            }
        }

        return $urlKeys;
    }

    /**
     * @return string|null the request path to use, or null to skip this rewrite
     */
    private function resolveConflict(
        BatchContext $context,
        string $sku,
        int $storeId,
        string $requestPath,
        string $strategy
    ): ?string {
        switch ($strategy) {
            case Config::URL_CONFLICT_APPEND:
                $suffix = $this->urlRewriteResource->getProductUrlSuffix($storeId);
                $base = $suffix !== '' && str_ends_with($requestPath, $suffix)
                    ? substr($requestPath, 0, -strlen($suffix))
                    : $requestPath;
                $unique = $base . '-' . $context->getEntityId($sku) . $suffix;
                $context->addMessage($sku, sprintf(
                    'URL "%s" is taken in store %d; used "%s" instead.',
                    $requestPath,
                    $storeId,
                    $unique
                ));

                return $unique;
            case Config::URL_CONFLICT_ERROR:
                $context->fail($sku, sprintf('URL "%s" is already taken in store %d.', $requestPath, $storeId));

                return null;
            default:
                $context->addMessage($sku, sprintf(
                    'URL "%s" is taken in store %d; rewrite skipped.',
                    $requestPath,
                    $storeId
                ));

                return null;
        }
    }

    public function isEnabled(): bool
    {
        return true;
    }

    public function getSortOrder(): int
    {
        return 600;
    }
}
