<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Import\Model\ResourceModel;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\ScopeInterface;

/**
 * Direct writes to the url_rewrite table for product rewrites.
 */
class UrlRewrite
{
    private const INSERT_CHUNK = 1000;
    public const ENTITY_TYPE_PRODUCT = 'product';

    /**
     * @var array<int, string> store_id => product URL suffix
     */
    private array $suffixByStore = [];

    public function __construct(
        private readonly ResourceConnection $resourceConnection,
        private readonly ScopeConfigInterface $scopeConfig
    ) {
    }

    public function getProductUrlSuffix(int $storeId): string
    {
        if (!isset($this->suffixByStore[$storeId])) {
            $this->suffixByStore[$storeId] = (string)$this->scopeConfig->getValue(
                'catalog/seo/product_url_suffix',
                ScopeInterface::SCOPE_STORE,
                $storeId
            );
        }

        return $this->suffixByStore[$storeId];
    }

    /**
     * Request paths already taken by OTHER entities, per store.
     *
     * @param string[] $requestPaths
     * @param int[] $excludeEntityIds our own products, whose rewrites we may overwrite
     * @return array<int, array<string, true>> store_id => set of taken request paths
     */
    public function findConflicts(array $requestPaths, array $excludeEntityIds): array
    {
        if (!$requestPaths) {
            return [];
        }

        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                $this->resourceConnection->getTableName('url_rewrite'),
                ['store_id', 'request_path']
            )
            ->where('request_path IN (?)', $requestPaths);
        if ($excludeEntityIds) {
            $select->where(
                'NOT (entity_type = ? AND entity_id IN (' . implode(',', array_map('intval', $excludeEntityIds)) . '))',
                self::ENTITY_TYPE_PRODUCT
            );
        }

        $conflicts = [];
        foreach ($connection->fetchAll($select) as $row) {
            $conflicts[(int)$row['store_id']][$row['request_path']] = true;
        }

        return $conflicts;
    }

    /**
     * Replace the autogenerated product rewrites of the given entities:
     * stale rewrites (old url_keys) are removed, then new rows inserted.
     * Category-path product rewrites are a future expansion.
     *
     * @param int[] $entityIds
     * @param int[] $storeIds
     * @param array<int, array{entity_type: string, entity_id: int, request_path: string,
     *        target_path: string, redirect_type: int, store_id: int, is_autogenerated: int}> $rows
     */
    public function replaceProductRewrites(array $entityIds, array $storeIds, array $rows): void
    {
        if (!$entityIds || !$storeIds) {
            return;
        }

        $connection = $this->resourceConnection->getConnection();
        $table = $this->resourceConnection->getTableName('url_rewrite');

        $connection->delete($table, [
            'entity_type = ?' => self::ENTITY_TYPE_PRODUCT,
            'entity_id IN (?)' => $entityIds,
            'store_id IN (?)' => $storeIds,
            'is_autogenerated = ?' => 1,
            'redirect_type = ?' => 0,
        ]);

        foreach (array_chunk($rows, self::INSERT_CHUNK) as $chunk) {
            $connection->insertOnDuplicate($table, $chunk, ['target_path', 'redirect_type', 'is_autogenerated']);
        }
    }
}
