<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Import\Model\ResourceModel;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\ResourceConnection;
use Magento\Store\Model\ScopeInterface;

/**
 * Direct writes to the url_rewrite table for product rewrites.
 */
class UrlRewrite
{
    private const INSERT_CHUNK = 1000;
    public const ENTITY_TYPE_PRODUCT = 'product';
    private const PRODUCT_CATEGORY_TABLE = 'catalog_url_rewrite_product_category';

    /**
     * @var array<int, string> store_id => product URL suffix
     */
    private array $suffixByStore = [];

    /**
     * @var array<int, string> store_id => category URL suffix
     */
    private array $categorySuffixByStore = [];

    public function __construct(
        private readonly ResourceConnection $resourceConnection,
        private readonly ScopeConfigInterface $scopeConfig
    ) {
    }

    public function getProductUrlSuffix(int $storeId): string
    {
        if (!isset($this->suffixByStore[$storeId])) {
            $this->suffixByStore[$storeId] = (string)$this->scopeConfig->getValue(
                'catalog/seo/product_url_suffix',
                ScopeInterface::SCOPE_STORE,
                $storeId
            );
        }

        return $this->suffixByStore[$storeId];
    }

    public function getCategoryUrlSuffix(int $storeId): string
    {
        if (!isset($this->categorySuffixByStore[$storeId])) {
            $this->categorySuffixByStore[$storeId] = (string)$this->scopeConfig->getValue(
                'catalog/seo/category_url_suffix',
                ScopeInterface::SCOPE_STORE,
                $storeId
            );
        }

        return $this->categorySuffixByStore[$storeId];
    }

    /**
     * Whether the store generates category-path product rewrites
     * (catalog/seo/generate_category_product_rewrites). Mirrors core.
     */
    public function isCategoryRewritesEnabled(int $storeId): bool
    {
        return $this->scopeConfig->isSetFlag(
            'catalog/seo/generate_category_product_rewrites',
            ScopeInterface::SCOPE_STORE,
            $storeId
        );
    }

    /**
     * Whether the store keeps 301 redirects when a url_key changes
     * (catalog/seo/save_rewrites_history). Mirrors core.
     */
    public function isSaveRewritesHistory(int $storeId): bool
    {
        return $this->scopeConfig->isSetFlag(
            'catalog/seo/save_rewrites_history',
            ScopeInterface::SCOPE_STORE,
            $storeId
        );
    }

    /**
     * Request paths already taken by OTHER entities, per store.
     *
     * @param string[] $requestPaths
     * @param int[] $excludeEntityIds our own products, whose rewrites we may overwrite
     * @return array<int, array<string, true>> store_id => set of taken request paths
     */
    public function findConflicts(array $requestPaths, array $excludeEntityIds): array
    {
        if (!$requestPaths) {
            return [];
        }

        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                $this->resourceConnection->getTableName('url_rewrite'),
                ['store_id', 'request_path']
            )
            ->where('request_path IN (?)', $requestPaths);
        if ($excludeEntityIds) {
            $select->where(
                'NOT (entity_type = ? AND entity_id IN (' . implode(',', array_map('intval', $excludeEntityIds)) . '))',
                self::ENTITY_TYPE_PRODUCT
            );
        }

        $conflicts = [];
        foreach ($connection->fetchAll($select) as $row) {
            $conflicts[(int)$row['store_id']][$row['request_path']] = true;
        }

        return $conflicts;
    }

    /**
     * Current autogenerated (canonical + category-path) product rewrites, used
     * to diff old vs new request paths for 301 history.
     *
     * @param int[] $entityIds
     * @param int[] $storeIds
     * @return array<int, array{entity_id: int, store_id: int, request_path: string,
     *         target_path: string, metadata: ?string}>
     */
    public function getExistingAutogenerated(array $entityIds, array $storeIds): array
    {
        if (!$entityIds || !$storeIds) {
            return [];
        }

        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                $this->resourceConnection->getTableName('url_rewrite'),
                ['entity_id', 'store_id', 'request_path', 'target_path', 'metadata']
            )
            ->where('entity_type = ?', self::ENTITY_TYPE_PRODUCT)
            ->where('entity_id IN (?)', $entityIds)
            ->where('store_id IN (?)', $storeIds)
            ->where('is_autogenerated = ?', 1)
            ->where('redirect_type = ?', 0);

        $rows = [];
        foreach ($connection->fetchAll($select) as $row) {
            $rows[] = [
                'entity_id' => (int)$row['entity_id'],
                'store_id' => (int)$row['store_id'],
                'request_path' => (string)$row['request_path'],
                'target_path' => (string)$row['target_path'],
                'metadata' => $row['metadata'] !== null ? (string)$row['metadata'] : null,
            ];
        }

        return $rows;
    }

    /**
     * Delete the autogenerated (canonical + category-path) product rewrites of
     * the given entities/stores. Used to drop rewrites of products that became
     * not-visible. FK cascade removes their catalog_url_rewrite_product_category
     * rows. Existing 301 redirects (redirect_type != 0) are preserved.
     *
     * @param int[] $entityIds
     * @param int[] $storeIds
     */
    public function deleteAutogenerated(array $entityIds, array $storeIds): void
    {
        if (!$entityIds || !$storeIds) {
            return;
        }

        $this->resourceConnection->getConnection()->delete(
            $this->resourceConnection->getTableName('url_rewrite'),
            [
                'entity_type = ?' => self::ENTITY_TYPE_PRODUCT,
                'entity_id IN (?)' => $entityIds,
                'store_id IN (?)' => $storeIds,
                'is_autogenerated = ?' => 1,
                'redirect_type = ?' => 0,
            ]
        );
    }

    /**
     * Replace the autogenerated product rewrites of the given entities: stale
     * canonical/category rewrites are removed, then the new rows (canonical,
     * category-path, anchor, and 301 redirect rows) are inserted. Rows may
     * carry a `metadata` value (JSON `{"category_id":X}` for category rows,
     * null otherwise). Existing 301 rows are preserved by the delete clause.
     *
     * @param int[] $entityIds
     * @param int[] $storeIds
     * @param array<int, array{entity_type: string, entity_id: int, request_path: string,
     *        target_path: string, redirect_type: int, store_id: int, is_autogenerated: int,
     *        metadata: ?string}> $rows
     */
    public function replaceProductRewrites(array $entityIds, array $storeIds, array $rows): void
    {
        if (!$entityIds || !$storeIds) {
            return;
        }

        $this->deleteAutogenerated($entityIds, $storeIds);

        $connection = $this->resourceConnection->getConnection();
        $table = $this->resourceConnection->getTableName('url_rewrite');
        foreach (array_chunk($rows, self::INSERT_CHUNK) as $chunk) {
            $connection->insertOnDuplicate(
                $table,
                $chunk,
                ['target_path', 'redirect_type', 'is_autogenerated', 'metadata']
            );
        }
    }

    /**
     * Rebuild catalog_url_rewrite_product_category rows for the given
     * entities/stores from the just-written category-path rewrites (those
     * carrying category metadata). Old relations were cascade-deleted with
     * their url_rewrite rows in replaceProductRewrites().
     *
     * @param int[] $entityIds
     * @param int[] $storeIds
     */
    public function saveProductCategoryRelations(array $entityIds, array $storeIds): void
    {
        if (!$entityIds || !$storeIds) {
            return;
        }

        $connection = $this->resourceConnection->getConnection();
        $select = $connection->select()
            ->from(
                $this->resourceConnection->getTableName('url_rewrite'),
                ['url_rewrite_id', 'entity_id', 'metadata']
            )
            ->where('entity_type = ?', self::ENTITY_TYPE_PRODUCT)
            ->where('entity_id IN (?)', $entityIds)
            ->where('store_id IN (?)', $storeIds)
            ->where('is_autogenerated = ?', 1)
            ->where('redirect_type = ?', 0)
            ->where('metadata IS NOT NULL');

        $relations = [];
        foreach ($connection->fetchAll($select) as $row) {
            $decoded = json_decode((string)$row['metadata'], true);
            if (!is_array($decoded) || !isset($decoded['category_id'])) {
                continue;
            }
            $relations[] = [
                'url_rewrite_id' => (int)$row['url_rewrite_id'],
                'category_id' => (int)$decoded['category_id'],
                'product_id' => (int)$row['entity_id'],
            ];
        }

        if (!$relations) {
            return;
        }

        $relationTable = $this->resourceConnection->getTableName(self::PRODUCT_CATEGORY_TABLE);
        foreach (array_chunk($relations, self::INSERT_CHUNK) as $chunk) {
            $connection->insertOnDuplicate($relationTable, $chunk, ['category_id', 'product_id']);
        }
    }
}
