<?php
/**
 * Copyright © ReadyData. All rights reserved.
 */
declare(strict_types=1);

namespace ReadyData\Import\Test\Unit\Model\Processor;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use ReadyData\Import\Model\BatchContext;
use ReadyData\Import\Model\Cache\AttributeMetadataCache;
use ReadyData\Import\Model\Cache\StoreWebsiteMap;
use ReadyData\Import\Model\Config;
use ReadyData\Import\Model\Data\Product;
use ReadyData\Import\Model\Processor\EavValueProcessor;
use ReadyData\Import\Model\Processor\EntityProcessor;
use ReadyData\Import\Model\Processor\UrlRewrite\CategoryPathRewriteBuilder;
use ReadyData\Import\Model\Processor\UrlRewriteProcessor;
use ReadyData\Import\Model\Processor\WebsiteProcessor;
use ReadyData\Import\Model\ResourceModel\CategoryLink;
use ReadyData\Import\Model\ResourceModel\EavValue;
use ReadyData\Import\Model\ResourceModel\UrlRewrite;

class UrlRewriteProcessorTest extends TestCase
{
    private UrlRewrite&MockObject $urlRewriteResource;
    private EavValue&MockObject $eavValue;
    private AttributeMetadataCache&MockObject $attributeMetadataCache;
    private StoreWebsiteMap&MockObject $storeWebsiteMap;
    private Config&MockObject $config;
    private CategoryLink&MockObject $categoryLink;
    private CategoryPathRewriteBuilder&MockObject $categoryPathRewriteBuilder;
    private UrlRewriteProcessor $processor;

    /**
     * @var array{entityIds: int[], storeIds: int[], rows: array<int, array>}|null
     */
    private ?array $replaced = null;

    /**
     * @var array{entityIds: int[], storeIds: int[]}|null
     */
    private ?array $deleted = null;

    protected function setUp(): void
    {
        $this->urlRewriteResource = $this->createMock(UrlRewrite::class);
        $this->urlRewriteResource->method('getProductUrlSuffix')->willReturn('.html');
        $this->urlRewriteResource->method('findConflicts')->willReturn([]);
        $this->urlRewriteResource->method('replaceProductRewrites')->willReturnCallback(
            function (array $entityIds, array $storeIds, array $rows): void {
                $this->replaced = ['entityIds' => $entityIds, 'storeIds' => $storeIds, 'rows' => $rows];
            }
        );
        $this->urlRewriteResource->method('deleteAutogenerated')->willReturnCallback(
            function (array $entityIds, array $storeIds): void {
                $this->deleted = ['entityIds' => $entityIds, 'storeIds' => $storeIds];
            }
        );

        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValues')->willReturn([]);

        $this->attributeMetadataCache = $this->createMock(AttributeMetadataCache::class);

        $this->storeWebsiteMap = $this->createMock(StoreWebsiteMap::class);
        $this->storeWebsiteMap->method('getStoreIdsForWebsites')->willReturn([1]);

        $this->config = $this->createMock(Config::class);
        $this->config->method('getUrlRewriteConflictStrategy')->willReturn(Config::URL_CONFLICT_APPEND);

        $this->categoryLink = $this->createMock(CategoryLink::class);
        $this->categoryPathRewriteBuilder = $this->createMock(CategoryPathRewriteBuilder::class);

        $this->processor = new UrlRewriteProcessor(
            $this->urlRewriteResource,
            $this->eavValue,
            $this->attributeMetadataCache,
            $this->storeWebsiteMap,
            $this->config,
            $this->categoryLink,
            $this->categoryPathRewriteBuilder
        );
    }

    public function testSameBatchDuplicateUrlKeyIsDisambiguatedInsteadOfCollapsing(): void
    {
        $context = $this->createContext(['SKU-A' => 8454, 'SKU-B' => 8816], urlKey: 'shared-key');

        $this->processor->process($context);

        self::assertNotNull($this->replaced);
        $pathsByEntity = [];
        foreach ($this->replaced['rows'] as $row) {
            $pathsByEntity[$row['entity_id']] = $row['request_path'];
        }

        self::assertSame('shared-key.html', $pathsByEntity[8454]);
        self::assertSame('shared-key-8816.html', $pathsByEntity[8816]);
        self::assertSame([], $context->getMessages('SKU-A'));
        self::assertStringContainsString('is taken in store 1', $context->getMessages('SKU-B')[0]);
    }

    public function testCanonicalOnlyWhenCategoryRewritesDisabled(): void
    {
        $this->urlRewriteResource->method('isCategoryRewritesEnabled')->willReturn(false);

        $this->processor->process($this->createContext(['SKU-A' => 42], urlKey: 'white-shirt'));

        self::assertNotNull($this->replaced);
        self::assertCount(1, $this->replaced['rows']);
        self::assertSame('white-shirt.html', $this->replaced['rows'][0]['request_path']);
        self::assertNull($this->replaced['rows'][0]['metadata']);
    }

    public function testCategoryPathRewritesGeneratedWhenEnabled(): void
    {
        $this->urlRewriteResource->method('isCategoryRewritesEnabled')->willReturn(true);
        $this->categoryLink->method('getAssignments')->willReturn([42 => [5]]);
        $this->categoryPathRewriteBuilder->method('build')->willReturn([
            42 => [[
                'request_path' => 'men/tops/white-shirt.html',
                'target_path' => 'catalog/product/view/id/42/category/5',
                'category_id' => 5,
            ]],
        ]);
        $relations = null;
        $this->urlRewriteResource->method('saveProductCategoryRelations')->willReturnCallback(
            function (array $entityIds, array $storeIds) use (&$relations): void {
                $relations = ['entityIds' => $entityIds, 'storeIds' => $storeIds];
            }
        );

        $this->processor->process($this->createContext(['SKU-A' => 42], urlKey: 'white-shirt'));

        self::assertNotNull($this->replaced);
        $byPath = [];
        foreach ($this->replaced['rows'] as $row) {
            $byPath[$row['request_path']] = $row;
        }
        self::assertArrayHasKey('white-shirt.html', $byPath);
        self::assertNull($byPath['white-shirt.html']['metadata']);
        self::assertArrayHasKey('men/tops/white-shirt.html', $byPath);
        self::assertSame(
            'catalog/product/view/id/42/category/5',
            $byPath['men/tops/white-shirt.html']['target_path']
        );
        self::assertSame('{"category_id":"5"}', $byPath['men/tops/white-shirt.html']['metadata']);
        self::assertSame(['entityIds' => [42], 'storeIds' => [1]], $relations);
    }

    public function testNotVisibleProductProducesNoRewritesAndIsDeleted(): void
    {
        $this->attributeMetadataCache->method('get')->willReturnCallback(
            static fn (string $code): ?array => $code === 'visibility'
                ? ['attribute_id' => 77, 'attribute_code' => 'visibility', 'backend_type' => 'int',
                   'frontend_input' => 'select', 'is_global' => 1, 'is_required' => 0]
                : null
        );
        // link id 99 has visibility = 1 (Not Visible) at store 0.
        $this->eavValue = $this->createMock(EavValue::class);
        $this->eavValue->method('getValues')->willReturnCallback(
            static fn (string $type, int $attrId, array $linkIds, int $storeId = 0): array =>
                $type === 'int' && $attrId === 77 && $storeId === 0 ? [99 => 1] : []
        );
        $this->processor = new UrlRewriteProcessor(
            $this->urlRewriteResource,
            $this->eavValue,
            $this->attributeMetadataCache,
            $this->storeWebsiteMap,
            $this->config,
            $this->categoryLink,
            $this->categoryPathRewriteBuilder
        );

        $context = $this->createContext(['SKU-A' => 42], urlKey: 'white-shirt', linkIds: ['SKU-A' => 99]);
        $this->processor->process($context);

        self::assertNull($this->replaced, 'A not-visible product must produce no rewrites.');
        self::assertSame(['entityIds' => [42], 'storeIds' => [1]], $this->deleted);
    }

    public function testUrlKeyChangeProducesRedirectWhenHistoryEnabled(): void
    {
        $this->urlRewriteResource->method('isSaveRewritesHistory')->willReturn(true);
        $this->urlRewriteResource->method('getExistingAutogenerated')->willReturn([
            ['entity_id' => 42, 'store_id' => 1, 'request_path' => 'white-shirt.html',
             'target_path' => 'catalog/product/view/id/42', 'metadata' => null],
        ]);

        $this->processor->process($this->createContext(['SKU-A' => 42], urlKey: 'blue-shirt'));

        self::assertNotNull($this->replaced);
        $redirects = array_values(array_filter(
            $this->replaced['rows'],
            static fn (array $row): bool => $row['redirect_type'] === 301
        ));
        self::assertCount(1, $redirects);
        self::assertSame('white-shirt.html', $redirects[0]['request_path']);
        self::assertSame('blue-shirt.html', $redirects[0]['target_path']);
        self::assertSame(0, $redirects[0]['is_autogenerated']);
    }

    /**
     * @param array<string, int> $entityIdsBySku
     * @param array<string, int> $linkIds
     */
    private function createContext(array $entityIdsBySku, string $urlKey, array $linkIds = []): BatchContext
    {
        $products = [];
        $urlKeys = [];
        $websiteIds = [];
        foreach ($entityIdsBySku as $sku => $entityId) {
            $products[] = (new Product())->setSku((string)$sku);
            $urlKeys[$sku] = $urlKey;
            $websiteIds[$sku] = [1];
        }

        $context = new BatchContext($products, 0);
        foreach ($entityIdsBySku as $sku => $entityId) {
            $context->setEntityId($sku, $entityId);
        }
        $context->set(EavValueProcessor::CONTEXT_URL_KEYS, $urlKeys);
        $context->set(WebsiteProcessor::CONTEXT_WEBSITE_IDS, $websiteIds);
        if ($linkIds) {
            $context->set(EntityProcessor::CONTEXT_LINK_IDS, $linkIds);
        }

        return $context;
    }
}
